### PR TITLE
DEVOPS-1835 Ability to use existing secret

### PR DESCRIPTION
**Pull request by xDmitriev**
* Helm: the ability to use existing Kubernetes secret for Wallarm API token
* CI:  chart testing in upgrade mode

### CODE REVIEW

**Comment by dmitry-j-mikhin** [comment]
It's really hard to read this commit history. It's better to reorganize in more clean way:
* https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/
* https://betterprogramming.pub/your-git-commit-history-should-read-like-a-history-book-heres-how-7f44d5df1801
* https://mainmatter.com/blog/2021/05/26/keeping-a-clean-git-history/

**Comment by xDmitriev** [comment]
> It's really hard to read this commit history. It's better to reorganize it in more clean way:

@dmitry-j-mikhin I do understand it, there are many commits because I had a lot of testing of  'chart test --upgrade' CI feature implementation. When we will merge this PR squash will be used.

**Comment by dmitry-j-mikhin** [comment]
Squashing is also not so good. You mix different type of changes altogether. It's better to keep them split - yaml reformatting, changes for improved testing, changes for secret handling. Please check:
* https://dev.to/wesen/squash-commits-considered-harmful-ob1
* https://medium.com/bananatag-engineering-blog/squash-merges-are-evil-171f55139c51

**Comment by xDmitriev** [comment]
No probs, I will clean the history. Testing improvements belong to the new feature (using existing secret).

**Comment by xDmitriev** [comment]
@dmitry-j-mikhin  review plz

**Review by dmitry-j-mikhin — APPROVED** [review]

**Pull request merged**
